export const comparables = [
  {
    db: 20,
    label: "Rustling Leaves",
    icon: "leaves",
    comment: "Too Quiet",
  },
  {
    db: 30,
    label: "Whisper",
    icon: "whisper",
    comment: "Too Quiet",
  },
  {
    db: 40,
    label: "Library",
    icon: "library",
    comment: "Too Quiet",
  },
  {
    db: 50,
    label: "Rain",
    icon: "rain",
    comment: "Soft",
  },
  {
    db: 60,
    label: "Conversation",
    icon: "conversation",
    comment: "Moderate",
  },
  {
    db: 70,
    label: "Vacuum",
    icon: "vacuum",
    comment: "Loud",
  },
  {
    db: 80,
    label: "Alarm Clock",
    icon: "alarm",
    comment: "Loud",
  },
  {
    db: 90,
    label: "Lawn Mower",
    icon: "mower",
    comment: "Over 85db for 30 minutes can cause hearing loss",
  },
  {
    db: 100,
    label: "Snowmobiles",
    icon: "snow",
    comment: "Uncomfortably loud",
  },
  {
    db: 110,
    label: "Stadium",
    icon: "stadium",
    comment: "Uncomfortably loud",
  },
  {
    db: 120,
    label: "Jet Planes",
    icon: "jet",
    comment: "Dangerous over 30 seconds",
  },
  {
    db: 130,
    label: "Ambulance",
    icon: "ambulance",
    comment: "Dangerous over 30 seconds",
  },
  {
    db: 140,
    label: "Gun Shots",
    icon: "gun",
    comment: "Call the cops?",
  },
];
