const comparables = [
  {
    db: 20,
    name: "Rustling Leaves",
    icon: "",
    comment: "Too Quiet",
  },
  {
    db: 30,
    name: "Whisper",
    icon: "",
    comment: "Too Quiet",
  },
  {
    db: 40,
    name: "Library",
    icon: "",
    comment: "Too Quiet",
  },
  {
    db: 50,
    name: "Rain",
    icon: "",
    comment: "Soft",
  },
  {
    db: 60,
    name: "Conversation",
    icon: "",
    comment: "Moderate",
  },
  {
    db: 70,
    name: "Vacuum",
    icon: "",
    comment: "Loud",
  },
  {
    db: 80,
    name: "Alarm Clock",
    icon: "",
    comment: "Loud",
  },
  {
    db: 90,
    name: "Lawn Mower",
    icon: "Over 85db for 30 minutes can cause hearing loss",
    comment: "",
  },
  {
    db: 100,
    name: "Snowmobiles",
    icon: "",
    comment: "Uncomfortably loud",
  },
  {
    db: 110,
    name: "Stadium",
    icon: "",
    comment: "Uncomfortably loud",
  },
  {
    db: 120,
    name: "Jet Planes",
    icon: "",
    comment: "Dangerous over 30 seconds",
  },
  {
    db: 130,
    name: "Ambulance",
    icon: "",
    comment: "Dangerous over 30 seconds",
  },
  {
    db: 140,
    name: "Gun Shots",
    icon: "",
    comment: "Call the cops?",
  },
];
